### ISSUE TITLE
Random WS Connection

### ISSUE THREAD

**Issue by Darker-Ink** [Votion-Development/Dashactyl-v2#15]
[At Line 22](https://github.com/Votion-Development/Dashactyl-v2/blob/main/frontend/src/Components/Headers/HeaderStats.jsx#L22) in `/frontend/src/Components/Headers/HeaderStats.jsx` There is a WS connection to a random URL. Is this meant to be there?

**Comment by real2two** [comment]
https://github.com/Votion-Development/Dashactyl-v2/blob/94c1c313347810462272cf84befa531656c6796e/frontend/src/Components/Sidebar/Sidebar.jsx#L20 same here

**Comment by JamieGrimwood** [comment]
Thanks for pointing it out, it was just how it was while i was developing it as I ran the frontend and backend separately. Should be fixed now.
