### ISSUE TITLE
Dash Renewal Not Working

### ISSUE THREAD

**Issue by ayush0662** [Votion-Development/Dashactyl-v2#21]
**Describe the bug**
The renew system was not working? When I renew server its show success but in Ptero it still suspended.

**To Reproduce**
1. Go to 'Manage Option'
2. Then click on 'Renew Button'
3. It will popup a msg which shows  'Success'
4. Then go to ptero server panel, there you will see nothing will happen. It still suspended.

**Expected behavior**
I just want to you to solve this as soon as you can. Its 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 1.0.0

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 11
 - Browser: Chrome
 - Version: 1.0.0

**Comment by JamieGrimwood** [comment]
The renew system adds a week onto the renewal time, I need to make it add a week onto the time that it was renewed from. Thanks for pointing this out.

**Comment by JamieGrimwood** [comment]
This should not be fixed in the latest update.
